version: '3'
services:
  api:
    build: 
      context: ./apps/server
      dockerfile: Dockerfile
    environment:
      - PORT=4000
      - NODE_ENV=development
    env_file:
      - ./apps/server/.env.local
    volumes:
      - ./apps/server:/app
      - /app/node_modules
    depends_on:
      - postgres
  client:
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    env_file:
      - ./apps/client/.env.local
    volumes:
      - ./apps/client:/app
      - /app/node_modules
    depends_on:
      - api
  postgres:
    image: ankane/pgvector
    restart: on-failure
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./apps/server/.env.local
  