version: '3'
services:
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - PORT=4000
      - NODE_ENV=development
    env_file:
      - ./server/.env.local
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - postgres
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    env_file:
      - ./client/.env.local
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api
  postgres:
    image: ankane/pgvector
    restart: on-failure
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ./server/.env.local
  