/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as AuthedChatsChatIdIndexRouteImport } from './routes/_authed/chats.$chatId/index'
import { Route as AuthedChatsChatIdResourcesRouteImport } from './routes/_authed/chats.$chatId/resources'
import { Route as AuthedChatsChatIdSettingsRouteImport } from './routes/_authed/chats.$chatId/settings'
import { Route as AuthedChatsChatIdSetupRouteImport } from './routes/_authed/chats.$chatId/setup'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedChatsChatIdIndexRoute = AuthedChatsChatIdIndexRouteImport.update({
  id: '/chats/$chatId/',
  path: '/chats/$chatId/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChatsChatIdResourcesRoute =
  AuthedChatsChatIdResourcesRouteImport.update({
    id: '/chats/$chatId/resources',
    path: '/chats/$chatId/resources',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedChatsChatIdSettingsRoute =
  AuthedChatsChatIdSettingsRouteImport.update({
    id: '/chats/$chatId/settings',
    path: '/chats/$chatId/settings',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedChatsChatIdSetupRoute = AuthedChatsChatIdSetupRouteImport.update({
  id: '/chats/$chatId/setup',
  path: '/chats/$chatId/setup',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/chat/$id': typeof ChatIdRoute
  '/chats/$chatId/resources': typeof AuthedChatsChatIdResourcesRoute
  '/chats/$chatId/settings': typeof AuthedChatsChatIdSettingsRoute
  '/chats/$chatId/setup': typeof AuthedChatsChatIdSetupRoute
  '/chats/$chatId/': typeof AuthedChatsChatIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/chat/$id': typeof ChatIdRoute
  '/': typeof AuthedIndexRoute
  '/chats/$chatId/resources': typeof AuthedChatsChatIdResourcesRoute
  '/chats/$chatId/settings': typeof AuthedChatsChatIdSettingsRoute
  '/chats/$chatId/setup': typeof AuthedChatsChatIdSetupRoute
  '/chats/$chatId': typeof AuthedChatsChatIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/chat/$id': typeof ChatIdRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/chats/$chatId/resources': typeof AuthedChatsChatIdResourcesRoute
  '/_authed/chats/$chatId/settings': typeof AuthedChatsChatIdSettingsRoute
  '/_authed/chats/$chatId/setup': typeof AuthedChatsChatIdSetupRoute
  '/_authed/chats/$chatId/': typeof AuthedChatsChatIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/chat/$id'
    | '/chats/$chatId/resources'
    | '/chats/$chatId/settings'
    | '/chats/$chatId/setup'
    | '/chats/$chatId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/auth/callback'
    | '/chat/$id'
    | '/'
    | '/chats/$chatId/resources'
    | '/chats/$chatId/settings'
    | '/chats/$chatId/setup'
    | '/chats/$chatId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/auth/callback'
    | '/chat/$id'
    | '/_authed/'
    | '/_authed/chats/$chatId/resources'
    | '/_authed/chats/$chatId/settings'
    | '/_authed/chats/$chatId/setup'
    | '/_authed/chats/$chatId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ChatIdRoute: typeof ChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/chats/$chatId/': {
      id: '/_authed/chats/$chatId/'
      path: '/chats/$chatId'
      fullPath: '/chats/$chatId/'
      preLoaderRoute: typeof AuthedChatsChatIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chats/$chatId/resources': {
      id: '/_authed/chats/$chatId/resources'
      path: '/chats/$chatId/resources'
      fullPath: '/chats/$chatId/resources'
      preLoaderRoute: typeof AuthedChatsChatIdResourcesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chats/$chatId/settings': {
      id: '/_authed/chats/$chatId/settings'
      path: '/chats/$chatId/settings'
      fullPath: '/chats/$chatId/settings'
      preLoaderRoute: typeof AuthedChatsChatIdSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/chats/$chatId/setup': {
      id: '/_authed/chats/$chatId/setup'
      path: '/chats/$chatId/setup'
      fullPath: '/chats/$chatId/setup'
      preLoaderRoute: typeof AuthedChatsChatIdSetupRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedChatsChatIdResourcesRoute: typeof AuthedChatsChatIdResourcesRoute
  AuthedChatsChatIdSettingsRoute: typeof AuthedChatsChatIdSettingsRoute
  AuthedChatsChatIdSetupRoute: typeof AuthedChatsChatIdSetupRoute
  AuthedChatsChatIdIndexRoute: typeof AuthedChatsChatIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedChatsChatIdResourcesRoute: AuthedChatsChatIdResourcesRoute,
  AuthedChatsChatIdSettingsRoute: AuthedChatsChatIdSettingsRoute,
  AuthedChatsChatIdSetupRoute: AuthedChatsChatIdSetupRoute,
  AuthedChatsChatIdIndexRoute: AuthedChatsChatIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ChatIdRoute: ChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
