/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedResourcesRouteImport } from './routes/_authed/resources'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ChatIdRouteImport } from './routes/chat.$id'
import { Route as AuthedOnboardingIndexRouteImport } from './routes/_authed/onboarding/index'
import { Route as AuthedOnboardingResourcesRouteImport } from './routes/_authed/onboarding/resources'
import { Route as AuthedOnboardingShareRouteImport } from './routes/_authed/onboarding/share'
import { Route as AuthedOnboardingStartersRouteImport } from './routes/_authed/onboarding/starters'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResourcesRoute = AuthedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOnboardingIndexRoute = AuthedOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingResourcesRoute =
  AuthedOnboardingResourcesRouteImport.update({
    id: '/onboarding/resources',
    path: '/onboarding/resources',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOnboardingShareRoute = AuthedOnboardingShareRouteImport.update({
  id: '/onboarding/share',
  path: '/onboarding/share',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingStartersRoute =
  AuthedOnboardingStartersRouteImport.update({
    id: '/onboarding/starters',
    path: '/onboarding/starters',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/resources': typeof AuthedResourcesRoute
  '/settings': typeof AuthedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/chat/$id': typeof ChatIdRoute
  '/onboarding/resources': typeof AuthedOnboardingResourcesRoute
  '/onboarding/share': typeof AuthedOnboardingShareRoute
  '/onboarding/starters': typeof AuthedOnboardingStartersRoute
  '/onboarding/': typeof AuthedOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/resources': typeof AuthedResourcesRoute
  '/settings': typeof AuthedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/chat/$id': typeof ChatIdRoute
  '/': typeof AuthedIndexRoute
  '/onboarding/resources': typeof AuthedOnboardingResourcesRoute
  '/onboarding/share': typeof AuthedOnboardingShareRoute
  '/onboarding/starters': typeof AuthedOnboardingStartersRoute
  '/onboarding': typeof AuthedOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/resources': typeof AuthedResourcesRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/chat/$id': typeof ChatIdRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/onboarding/resources': typeof AuthedOnboardingResourcesRoute
  '/_authed/onboarding/share': typeof AuthedOnboardingShareRoute
  '/_authed/onboarding/starters': typeof AuthedOnboardingStartersRoute
  '/_authed/onboarding/': typeof AuthedOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/resources'
    | '/settings'
    | '/auth/callback'
    | '/chat/$id'
    | '/onboarding/resources'
    | '/onboarding/share'
    | '/onboarding/starters'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/resources'
    | '/settings'
    | '/auth/callback'
    | '/chat/$id'
    | '/'
    | '/onboarding/resources'
    | '/onboarding/share'
    | '/onboarding/starters'
    | '/onboarding'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/resources'
    | '/_authed/settings'
    | '/auth/callback'
    | '/chat/$id'
    | '/_authed/'
    | '/_authed/onboarding/resources'
    | '/_authed/onboarding/share'
    | '/_authed/onboarding/starters'
    | '/_authed/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ChatIdRoute: typeof ChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/resources': {
      id: '/_authed/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthedResourcesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/onboarding/': {
      id: '/_authed/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthedOnboardingIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding/resources': {
      id: '/_authed/onboarding/resources'
      path: '/onboarding/resources'
      fullPath: '/onboarding/resources'
      preLoaderRoute: typeof AuthedOnboardingResourcesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding/share': {
      id: '/_authed/onboarding/share'
      path: '/onboarding/share'
      fullPath: '/onboarding/share'
      preLoaderRoute: typeof AuthedOnboardingShareRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding/starters': {
      id: '/_authed/onboarding/starters'
      path: '/onboarding/starters'
      fullPath: '/onboarding/starters'
      preLoaderRoute: typeof AuthedOnboardingStartersRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedResourcesRoute: typeof AuthedResourcesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedOnboardingResourcesRoute: typeof AuthedOnboardingResourcesRoute
  AuthedOnboardingShareRoute: typeof AuthedOnboardingShareRoute
  AuthedOnboardingStartersRoute: typeof AuthedOnboardingStartersRoute
  AuthedOnboardingIndexRoute: typeof AuthedOnboardingIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedResourcesRoute: AuthedResourcesRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedOnboardingResourcesRoute: AuthedOnboardingResourcesRoute,
  AuthedOnboardingShareRoute: AuthedOnboardingShareRoute,
  AuthedOnboardingStartersRoute: AuthedOnboardingStartersRoute,
  AuthedOnboardingIndexRoute: AuthedOnboardingIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ChatIdRoute: ChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
