
# Manual testing http requests with extension REST Client

### GET /api/chats gets all the available chats for the user
GET http://{{host}}/api/chats
Authorization: Bearer {{token}}

### POST /api/chats creates a new chat from a file loading embeddings for it
POST http://{{host}}/api/chats
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="file"; filename="example.txt"
Content-Type: text/plain

< ./data/example.txt
------boundary--

### GET /api/chats/:id Get the chat with the messages available
GET http://{{host}}/api/chats/5b6c4768-ec28-4426-96e2-15e1692feba5
Authorization: Bearer {{token}}

### DELETE /api/chats/:id delete the chat with the given id
DELETE http://{{host}}/api/chats/2519bba2-2285-446c-a02d-e8fa14d6a30c
Authorization: Bearer {{token}}


### PUT /api/chats/:id add a message to the chat
POST  http://{{host}}/api/chats/5b6c4768-ec28-4426-96e2-15e1692feba5
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "message": "Who is juan?"
}



