
# Manual testing http requests with extension REST Client

### GET /api/chat gets the chat for the owner
GET http://{{host}}/api/chat
Authorization: Bearer {{token}}

### PUT /api/chat
PUT http://{{host}}/api/chat
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Chat 1"
}

### PUT /api/chat/logo Upload a logo for the chat
PUT http://{{host}}/api/chat/logo
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="file"; filename="example.txt"
Content-Type: image/jpg

< ./data/profile.jpg
------boundary--

### POST /api/chat/resources/web/inspect Checks urls that can be added as resources
POST http://{{host}}/api/chat/resources/web/inspect
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "url": "https://js.langchain.com/docs/use_cases/question_answering/streaming"
}

### POST /api/chat/resources/web Add a web resource
POST http://{{host}}/api/chat/resources/web
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "type": "web",
    "urls": ["https://js.langchain.com/docs/use_cases/question_answering/streaming"]
}

### DELETE /api/chat/resouces/:id Delete resource
DELETE http://{{host}}/api/chat/resources/2126e890-b2f9-40a5-9479-1f417192bb64
Authorization: Bearer {{token}}

### GET /api/chat/:id gets the chat for the consumer
GET http://{{host}}/api/chat/66261ae48daee07eb34ba3a4

### POST /api/chat/:id generate response for question
POST http://{{host}}/api/chat/66261ae48daee07eb34ba3a4
Content-Type: application/json

{
    "question": "How does streaming work with langchain?",
    "chatHistory": []
}
