
# Manual testing http requests with extension REST Client

### GET /api/chat gets the chat for the owner
GET http://{{host}}/api/chat
Authorization: Bearer {{token}}



### PUT /api/chat
PUT http://{{host}}/api/chat
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Chat 1"
}

### PUT /api/chat/logo Upload a logo for the chat
PUT http://{{host}}/api/chat/logo
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----boundary

------boundary
Content-Disposition: form-data; name="file"; filename="example.txt"
Content-Type: image/jpg

< ./data/profile.jpg
------boundary--

### POST /api/chat/resouces Upload a resource for the chat
POST http://{{host}}/api/chat/resources
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "url": "https://js.langchain.com/docs/get_started/introduction"
}

### DELETE /api/chat/resouces/:id Delete resource
DELETE http://{{host}}/api/chat/resources/e97fa1b3-4e04-4fa7-860c-7cf9bf03d9de
Authorization: Bearer {{token}}



### GET /api/chat/:id gets the chat for the consumer
GET http://{{host}}/api/chat/8e8c781c-d271-4f37-82de-b75e7df4c795
