
# Manual testing http requests with extension REST Client

### GET /users/whoami
GET http://{{host}}/api/users
Authorization: Bearer {{token}}


### PUT /users
PUT http://{{host}}/api/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "John Doe"
}
