HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 791
ETag: W/"317-sPpy8CGFeozJzU7l1tq2qXW3yeg"
Date: Sat, 06 Apr 2024 09:34:16 GMT
Connection: close

{"id":"fd64e2f6-3e8e-40cb-8024-a2e1d69e6c56","name":"Chat 1","logo":"https://lorem.com/ipsum.png","url":"https://lorem.com","conversationStarters":[],"published":false,"resources":[{"id":"d7816ae9-85ef-45f8-be25-d39df6ca9152","type":"website","data":"https://js.langchain.com/docs/use_cases/question_answering/streaming","embeddingIds":["clunwawl00000t77dhn5ghu8t","clunwawxx0001t77dkzdmny3z","clunwax7p0002t77dtcmijnwm","clunwaxhd0003t77d8ybgg7ej","clunwaxrw0004t77dggozikhx","clunway1t0005t77d4lxm2049","clunwaybj0006t77dbd0jd100","clunwaykr0007t77d2gmb551k","clunwayuv0008t77dtca9t742","clunwaz540009t77d8d7ffkqn","clunwaze9000at77dx1nkvsd0","clunwazol000bt77dt93l0mcd","clunwazzc000ct77dcovya164"],"createdAt":"2024-04-06T09:31:39.059Z","chatId":"fd64e2f6-3e8e-40cb-8024-a2e1d69e6c56"}]}